base_config:
  - configs/basics/fs2.yaml

task_cls: src.diffsinger_task.DiffSingerMIDITask
datasets: [
  'opencpop',
]
num_spk: 1
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

test_num: 0
valid_num: 0

pre_align_cls: data_gen.pre_align.SingingPreAlign
pre_align_args:
  txt_processor: zh_g2pM
  use_tone: false # for ZH
  forced_align: mfa
  use_sox: true
max_frames: 8000

audio_sample_rate: 44100
audio_num_mel_bins: 128
hop_size: 512            # Hop size.
fft_size: 2048           # FFT size.
win_size: 2048           # FFT size.
fmin: 40
fmax: 16000
min_level_db: -120

vocoder: NsfHifiGAN
vocoder_ckpt: checkpoints/nsf_hifigan/model
use_nsf: true

binarizer_cls: data_gen.opencpop.OpencpopBinarizer
binarization_args:
  with_wav: false
  with_spk_embed: false
  with_align: true
raw_data_dir: 'data/raw/opencpop/segments'
processed_data_dir: 'xxx'
binary_data_dir: 'data/binary/opencpop-midi-dp'
g2p_dictionary: dictionaries/opencpop-strict.txt
mel_vmin: -6. #-6.
mel_vmax: 1.5
wav2spec_eps: 1e-6
save_f0: true

pitch_extractor: 'parselmouth'
pitch_type: frame
# config for experiments

content_cond_steps: [ ] # [ 0, 10000 ]
spk_cond_steps: [ ] # [ 0, 10000 ]
spec_min: [-5]
spec_max: [0]
keep_bins: 128
mel_loss: "ssim:0.5|l1:0.5"
lambda_uv: 0.0
lambda_energy: 0.0
use_spk_id: false

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_spk_embed: false
use_gt_f0: false  #  for midi exp
use_gt_dur: false  # for further midi exp
lambda_f0: 1.0
use_uv: false
#lambda_uv: 1.0
#lambda_energy: 0.1
lambda_ph_dur: 0.3
lambda_sent_dur: 3.0
lambda_word_dur: 1.0
predictor_grad: 0.1
#pe_enable: true
#pe_ckpt: 'checkpoints/0102_xiaoma_pe'
pitch_loss: l2
diff_loss_type: l2

fs2_ckpt: ''  #

K_step: 1000
timesteps: 1000
max_beta: 0.02
lr: 0.0005
decay_steps: 50000
max_tokens: 80000
predictor_layers: 5
dilation_cycle_length: 4  # *
rel_pos: true
dur_predictor_layers: 5  # *
max_updates: 250000
gaussian_start: true
pndm_speedup: 10

hidden_size: 256
diff_decoder_type: 'wavenet'
schedule_type: 'linear'

residual_layers: 20
residual_channels: 512

# train and eval
gen_tgt_spk_id: -1
num_sanity_val_steps: 1
max_sentences: 48
val_check_interval: 2000
num_valid_plots: 10
